language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
script:
    - pip install "notebook>=4.0,<5.0"
    - mkdir -p /home/travis/.jupyter/nbconfig
    - jupyter notebook --generate-config
    - pip install jupyter_dashboards
    - jupyter dashboards install --user --symlink
    - jupyter dashboards activate
    - python setup.py sdist
    - pip install --no-use-wheel --no-deps dist/*.tar.gz
    - python -B -m unittest discover -s test

notifications:
    email:
        on_success: change
        on_failure: always
    slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4
